### ISSUE TITLE
How to generate testcases without running target programs?

### ISSUE THREAD

**Issue by viccon** [googleprojectzero/fuzzilli#1]
Hi, Is there any option to generate testcases without running target programs?

**Comment by saelo** [comment]
Unfortunately not. The problem is mainly that the fuzzer requires feedback for the generated samples (e.g. coverage, but also whether the sample executed successfully or caused a runtime exception) and will perform different steps (thus producing different follow-up samples) based on that. So running it without that kind of feedback currently does not make much sense.
