### ISSUE TITLE
Assertion Failure in AbstractInterpreter

### ISSUE THREAD

**Issue by WilliamParks** [googleprojectzero/fuzzilli#199]
I'm consistently triggering [this assertion error](https://github.com/googleprojectzero/fuzzilli/blob/master/Sources/Fuzzilli/FuzzIL/AbstractInterpreter.swift#L463) in AbstractInterpreter.

Printf style debugging shows that it's a `Dup` instruction, with the following stacktrace snippet
```
4    FuzzilliCli                        0x000055aef9a789e0 AbstractInterpreter.execute(_:) + 2902
5    FuzzilliCli                        0x000055aef9a334e0 ProgramBuilder.internalAppend(_:) + 1792
6    FuzzilliCli                        0x000055aef9a26ef0 ProgramBuilder.adopt(_:keepTypes:) + 420
7    FuzzilliCli                        0x000055aef9a277b0 ProgramBuilder.splice(from:at:) + 3007
8    FuzzilliCli                        0x000055aef9a29f10 ProgramBuilder.splice(from:) + 1319
9    FuzzilliCli                        0x000055aef9a2b5d1 <unavailable> + 3421649
10   FuzzilliCli                        0x000055aef99ba06c <unavailable> + 2957420
11   FuzzilliCli                        0x000055aef9a37f01 <unavailable> + 3473153
12   FuzzilliCli                        0x000055aef9ce8a80 withEqualProbability<A>(_:) + 103
13   FuzzilliCli                        0x000055aef9a2b130 ProgramBuilder.generateInternal() + 897
14   FuzzilliCli                        0x000055aef9a2b860 ProgramBuilder.generate(n:) + 219
15   FuzzilliCli                        0x000055aef9ba9370 CodeGenMutator.mutate(_:_:) + 474
16   FuzzilliCli                        0x000055aef9ba6e74 <unavailable> + 4976244
17   FuzzilliCli                        0x000055aef9a258d0 ProgramBuilder.adopting(from:_:) + 84
18   FuzzilliCli                        0x000055aef9ba6080 BaseInstructionMutator.mutate(_:using:) + 2212
19   FuzzilliCli                        0x000055aef9bb0880 Mutator.mutate(_:for:) + 257
20   FuzzilliCli                        0x000055aef9a13100 MutationEngine.fuzzOne(_:) + 3084
```

I've found it when resuming a previous session, and merging in samples from a different run, using the following flags `./FuzzilliCli --profile=v8 --timeout=400 --importCorpusNewCov=./aggressive_min_v8_with_types --collectRuntimeTypes --storagePath=./foo --jobs=60 ./d8`

**Comment by saelo** [comment]
I've briefly tried reproducing this issue but no luck so far. If it's really a `Dup` instruction, then something must've set the type of its input variable to `.anything` or `.nothing`. If the AI did that, it should've triggered that assertion earlier, so probably it was something else. I've [moved the assert into `setType`](https://github.com/googleprojectzero/fuzzilli/commit/7382d5f511d7be0b46e480d73d877600ecdf4c91), which should now catch that situation earlier (while still catching the AI doing it). My current best guess is that somehow the runtime type collection ends up returning `.anything` or `.nothing`, and then that type overrides the type inferred by AI. Then, the `Dup` just causes that type to be used as an output type again, and thus crashes in that assert.

Also, please use permalinks ("Copy permalink") next time since the link now pointed [here](https://github.com/googleprojectzero/fuzzilli/blob/56a041e08993dcba14494142fd14d19df7e7a3d3/Sources/Fuzzilli/FuzzIL/AbstractInterpreter.swift#L463) :D

**Comment by WilliamParks** [comment]
There's a bug in the types that the compiler provides (the values for `unknown` and `anything` were backward). Using the inspect functionality, this looked to result in some highly improper types, which I think caused this after propagating. I'll get a PR together to close this issue!

**Comment by saelo** [comment]
Great, thanks for investigating!
