### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value (Symbol Constructor)

### ISSUE THREAD

**Issue by Zon8Research** [googleprojectzero/fuzzilli#211]
As per https://github.com/googleprojectzero/fuzzilli/issues/209 and https://github.com/googleprojectzero/fuzzilli/issues/210, I've been running Fuzzilli in debug mode to try flush out some crashes that have been happening (mainly) when using hybrid and multi modes.

To begin with, the following crash occured:

```
fuzzilli/ProgramBuilder.swift:482: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    libswiftCore.so                    0x00007f711d076210 swift_reportError + 50
1    libswiftCore.so                    0x00007f711d0eafc0 _swift_stdlib_reportFatalErrorInFile + 112
2    libswiftCore.so                    0x00007f711cdd4f56 <unavailable> + 1425238
3    libswiftCore.so                    0x00007f711cdd4b7f <unavailable> + 1424255
4    libswiftCore.so                    0x00007f711cdd491c <unavailable> + 1423644
5    libswiftCore.so                    0x00007f711cdd4430 _assertionFailure(_:_:file:line:flags:) + 441
6    FuzzilliCli                        0x00005558c4a8571f <unavailable> + 1013535
7    FuzzilliCli                        0x00005558c4a857a4 <unavailable> + 1013668
8    FuzzilliCli                        0x00005558c4a96c14 <unavailable> + 1084436
9    libswiftCore.so                    0x00007f711cdbb8d0 Collection.map<A>(_:) + 524
10   FuzzilliCli                        0x00005558c4a83d01 <unavailable> + 1006849
11   FuzzilliCli                        0x00005558c4a7f1b7 <unavailable> + 987575
12   FuzzilliCli                        0x00005558c4a9f587 <unavailable> + 1119623
13   FuzzilliCli                        0x00005558c4a997f9 <unavailable> + 1095673
14   FuzzilliCli                        0x00005558c4a10ed1 <unavailable> + 536273
15   FuzzilliCli                        0x00005558c4a11374 <unavailable> + 537460
16   FuzzilliCli                        0x00005558c4a12191 <unavailable> + 541073
17   FuzzilliCli                        0x00005558c4a6eea0 <unavailable> + 921248
18   FuzzilliCli                        0x00005558c4a6f731 <unavailable> + 923441
19   FuzzilliCli                        0x00005558c4b5ae8d <unavailable> + 1887885
```

On line:

```
            let constructionSignature = fuzzer.environment.type(ofBuiltin: group).constructorSignature!
```

This wasn't much help, so the following assertion was added to further debug this:

```
            assert(fuzzer.environment.type(ofBuiltin: group).constructorSignature != nil, "Constructor signature is nil for group: \(group) type: \(type)")
```

This then returned the following assertion, indicating the problem is with the Symbol type:

```
Fuzzilli/ProgramBuilder.swift:480: Assertion failed: Constructor signature is nil for group: Symbol type: .object(ofGroup: Symbol, withProperties: ["description", "__proto__"])
```

This is possibly due to the fact that Fuzzilli has a [Symbol contructor](https://github.com/googleprojectzero/fuzzilli/blob/224ce58c40eea9983774cb69edb41021d80eca52/Sources/Fuzzilli/Core/JavaScriptEnvironment.swift#L367), however Symbol uses an incomplete constructor [as per MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol):

```
Creates a new Symbol object. It is incomplete as a constructor because it does not support the syntax "new Symbol()".
```

A temporary fix to stop this crash from happening was to comment out the following line:

https://github.com/googleprojectzero/fuzzilli/blob/224ce58c40eea9983774cb69edb41021d80eca52/Sources/Fuzzilli/Core/JavaScriptEnvironment.swift#L106

Input would be appreciated on how to fix this properly!

**Comment by saelo** [comment]
Nice, thanks for your help here again! 

So "Symbol" is (was) marked as non-constructable [here](https://github.com/googleprojectzero/fuzzilli/blob/5e216671fc172af60489b59c836c638cded74c9b/Sources/Fuzzilli/Core/JavaScriptEnvironment.swift#L71), and so shouldn't be selected [here](https://github.com/googleprojectzero/fuzzilli/blob/5e216671fc172af60489b59c836c638cded74c9b/Sources/Fuzzilli/Core/ProgramTemplate.swift#L84). However, there is [this](https://github.com/googleprojectzero/fuzzilli/blob/5e216671fc172af60489b59c836c638cded74c9b/Sources/Fuzzilli/Core/JavaScriptEnvironment.swift#L978) method which requires a Symbol as input, and so that would probably lead to `generateVariable` being called with that and crashing. Might be wrong though.

I think really, "Symbol" shouldn't be in the list of non-constructable objects in the first place. Unfortunately, this is a special case where a Constructor builtin exists, but isn't a constructor :/ I guess one way to "solve" this is simply to support constructing objects through a function call as opposed to a constructor call in 'generateVariable'.
I took at shoot at implementing this in commit https://github.com/googleprojectzero/fuzzilli/commit/aeaf5758c4ccfa1b71991bfa387e4b26ae6486d1. Can you check if that fixes the issue?

**Comment by Zon8Research** [comment]
So I've been using the commented symbol fix for around 8 or 9 days without a crash. I've just updated to the latest changes, and Fuzzilli died overnight.

Unfortunately I don't have a trace, since I was running on release mode. But it indicates either one of the new changes may have introduced crash or that this fix isn't working properly. 

I'll run on debug for a while and see if I can figure out whats happening.

**Comment by saelo** [comment]
Ok thanks for checking! I'll also leave a bunch of debug instances with `--engine=multi` running over the weekend and see if something crashes

**Comment by saelo** [comment]
Some more fixes: https://github.com/googleprojectzero/fuzzilli/commit/f31ba8ee5f1d7d5f338a0d047a55d21b13494f7a We should probably add a bunch of tests for that method...

**Comment by Zon8Research** [comment]
I've not seen this crash since rerunning with debug anymore. Closing, if I see it again I'll reopen!
