### ISSUE TITLE
Question about fuzzil IR with statement

### ISSUE THREAD

**Issue by oicu0619** [googleprojectzero/fuzzilli#221]
i am working on compile JS to fuzzil iR, and i have a question. What should this kind of JS compile to:

a={ a: 1, b: 2 };
with (a) {
	console.log(a);
        someFunction();
	console.log(a);
}

In the latter console.log, 'a' might refer to object a's property a , or also refer to object a , depends on whether the signature of object 'a' changed in the middle by the function. What should be the proper FuzzIl Operation here?
Thanks a lot for the help!

**Comment by saelo** [comment]
Hi! So `with` statements are unfortunately a bit tricky. You could try the following:
```
v3 <- CreateObject ...
StoreToScope 'a', v3
BeginWith v3
    v4 <- LoadFromScope 'a'
    ...
```

which might work, but is definitely a hack and not really meant for that. I think a better solution, which requires some changes to Fuzzilli though, would be to rename `StoreToScope` and `LoadFromScope` to `StoreNamedVariable` and `LoadNamedVariable` and allow them in every context, [not just inside `with`](https://github.com/googleprojectzero/fuzzilli/blob/22d9a3708450027dd8dc4982263d0c84991f4cd7/Sources/Fuzzilli/Core/CodeGenerators.swift#L675). They would then also just lift to `$name = $expr` and `$name`, and essentially assign a name to a variable. Then they could be used exactly for the kind of code you listed, where the name of a variable is important.

**Comment by oicu0619** [comment]
Thanks for the reply and for the great tool!
What does LoadFromScope and StoreToScope meant for? I observed that it will just lift to javascript like
```
const v3 = a
``` 
Also, should i compile global variables to StoreToScope and LoadFromScope? Or should i compile global variable to something like 
```
v3 <- Loadbuiltin 'globalThis'
v4 <- Loadproperty v3, 'a'
```
Or should compile it to something else? I think both way will keep the original name of the global variable and not renaming them. 
By the way i have a stupid question... what's the benefit of wrapping everything inside a function main(){} and then invoke it? thanks!

**Comment by saelo** [comment]
Yeah `LoadFromScope` and `StoreToScope` were meant specifically to just be used inside `With` to access properties of the context object. But it's not really a good solution and so I've created https://github.com/googleprojectzero/fuzzilli/issues/224 to document that.

Since `StoreToScope`/`LoadFromScope` were meant to just be used inside `With`, it's probably better to compiler global variable accesses to explicit `StoreProperty`/`LoadProperty` on the global object for now.

One benefit of wrapping all code into a main function is that Fuzzilli can e.g. prevent that function from [being JIT compiled itself](https://github.com/googleprojectzero/fuzzilli/blob/bc057d1eb2d47878b700022e59409e974bd01597/Sources/FuzzilliCli/Profiles/JSCProfile.swift#L59), which might be useful to prevent OSR-entry into JIT code in the middle of a function and instead enter JIT-compiled function at a function call boundary.
