### ISSUE TITLE
Warning "Failed to find edge in map" when using MarkovCorpus

### ISSUE THREAD

**Issue by saelo** [googleprojectzero/fuzzilli#223]
Transferring the discussion from https://github.com/googleprojectzero/fuzzilli/pull/171#issuecomment-864851774 to a new issue.

**Comment by saelo** [comment]
So @WilliamParks from the ideas you listed in the original pull request, currently I think the idea that crashes set edges that are then "leaked" sounds most likely to me. There is [a mechanism](https://github.com/googleprojectzero/fuzzilli/blob/22d9a3708450027dd8dc4982263d0c84991f4cd7/Sources/Fuzzilli/Fuzzer.swift#L643) that should prevent a new fuzzing iterations before the previous iteration finished (and that includes minimization etc.), so I don't think that there is some kind of race condition there. On the other hand, a crashing sample will, as you said, cause `ProgramCoverageEvaluator.evaluateCrash` -> `cov_evaluate_crash` -> `internal_evaluate` to be called, and that will update the edge counts. I'll quickly hack something together that stops it from updating the edge counts when evaluating crashes and see if that fixes the issue.

**Comment by saelo** [comment]
Update: I'm still getting a few `Failed to find edge in map` warnings (seems to be less though) even with that change and even on instances that have zero crashes, so probably that wasn't the only reason.

**Comment by WilliamParks** [comment]
Hmm, interesting.

I haven't worked out the exact path that would cause the problem, but could there be an issue with `ThreadSync` and `NetworkSync` causing executions without entering the fuzzGroup DispatchGroup?

For example, `handleMessageInternal` in `NetworkSync` then calls `fuzzer.importProgram`, `importProgram` and finally `processInteresting' without ever entering `fuzzGroup`

**Comment by WilliamParks** [comment]
Thinking about this more, I'm pretty sure `[evaluateAndIntersect](https://github.com/googleprojectzero/fuzzilli/blob/bc057d1eb2d47878b700022e59409e974bd01597/Sources/Fuzzilli/Evaluation/ProgramCoverageEvaluator.swift#L213)` leaks edges if said edge is over the resetLimit, as that edge will not be returned, but also will not be reset.

**Comment by WilliamParks** [comment]
I've got a draft fix for the resetLimit issue, which doesn't seem to fully fix the problem. I'm in the process of adding instrumentation to track the source of each edge, so we can see where the unfound ones are coming from.

**Comment by WilliamParks** [comment]
In fixing the issue with handling edges past their reset limit, `evaluateAndInterset` may need to return a `CovEdgeSet` with more edges than either individual execution. This happens when each execution finds unique non-deterministic edges past their reset limit.

What are your thoughts on the proper way to allocating more memory? My understanding is that `UnsafeMutablePointer<UInt32>.allocate` is not guaranteed to use `malloc` (per my brief search, but I'm not 100% sure ), while using `realloc` would require switching to using `UnsafeMutableRawPointer`.

WDYT?

**Comment by WilliamParks** [comment]
Additionally, my debugging efforts show that there could be a race condition between the two passes in [`libcoverage`](https://github.com/googleprojectzero/fuzzilli/blob/22f3379d57d6015065ca4862f164ef9b83b54b23/Sources/libcoverage/coverage.c#L126). The JS engine process will continue to run while the Fuzzilli process checks for new coverage, and then updates edge counts, leading to some edges having counts > 1 but not reported as new coverage.

My two ideas are either
- Accept these edges that will not be found when Markov corpus regenerates its program list
- Combine edge counts and new coverage detection into a single pass, with only one call to `edge(context->shmem->edges, i)`

Thoughts?

**Comment by WilliamParks** [comment]
@saelo WDYT?

**Comment by saelo** [comment]
Sorry, I'm pretty slow currently... :/
Right so I'm not super enthusiastic about either change... it seems weird for something called `evaluateAnd*Intersect*` to return a larger set than its inputs, and doing the single pass (to fix the race condition) would make it harder to only selectively enable edge counts I think?
Do you have an estimate about how "bad" these issues are? I'm wondering if, instead, it'd be simpler and still acceptable to just document the circumstances under which edges are being leaked, then add some little "fixup" code to e.g. the MarkovCorpus to deal with it by e.g. disallowing those edges or adding a dummy program for them (or, maybe even simpler, not treating this as a warning, and instead emitting a warning if more than X% of edges are missing or something like that). WDYT about that?

**Comment by WilliamParks** [comment]
Oh! No worries. I hope all is well!

My personal testing shows that it is fairly infrequent, but I don't have a good grasp on the actual percentage.

With how long we've been looking at this, I can't remember what we settled on for the desired behavior. Are we looking to include an edge that just hit the reset limit, so whatever test case triggered reset N+1 is added to the corpus? Alternatively, at reset N+1, the coverage evaluator could no longer tracks that edge, and filter the list of reset edges out when it returns overall edge counts.

I can make two changes:
- Make sure the inclusion/exclusion of reset edges is implemented properly, ignoring the issues with the passes in libcoverage, and the case where `evaluateAndInterset` increases in size
- Add tracking/reporting on improperly tracked reset edges. This could be done with a pass over all tracked edges when the Markov Corpus regenerates its program list, and it could report an error if the number of edges without corresponding programs is over a certain percentage. Since program list regeneration happens infrequently, this shouldn't be much of an overall performance hit.

Thanks!
