### ISSUE TITLE
Enhance Object creation

### ISSUE THREAD

**Issue by amarekano** [googleprojectzero/fuzzilli#253]
Currently Object creation ops (i.e. `CreateObject` and `CreateObjectWithSpread`) only allows generating objects with data properties and spread elements. I would like to enhance these object creation that will allow generation of the following js object features:

* getters
* setters
* computed properties
* computed getters/setters

I've been thinking of a way to remodel these ops to support the features above and what I've come up with is a bit more radical and I'd like peoples thoughts on this. I'd like to introduce 9 new ops to support the existing and the new features of object creation. An example of which is listed below:

```
let obj <- BeginObjectCreation // 0 inputs and 1 output; isBeginBlock
	CreateProperty (name, variable) // generates simple data property; 1 inputs, 0 outputs
	
	CreateComputedProperty (variable, variable) // generates a computed data property; 2 inputs, 0 outputs	
	
	CreateSpreadProperty (name, variable) // spreads variable; 1 inputs, 0 outputs
	
	BeginGetter (name) // 0 inputs, 0 outputs
		...FuzzIL instructions
	
	BeginComputedGetter (variable) // 1 input, 0 outputs
		....FuzzIL instructions
	
	BeginSetter (name) // will have a default function signature with one param; 0 inputs, 0 outputs, 1 innerOutput
		....FuzzIL instructions
	
	BeginComputedSetter (name, variable) // will have a default function signature with one param; 1 input, 0 outputs, 1 innerOutput
		...FuzzIL instructions
EndObjectCreation
```

This model is very similar to the way `ClassDefinitions` have been modeled with `Begin*` ops being the start of a new block and `EndObjectCreation` closing the last opened block. However, `BeginObjectCreation` differs from `BeginClassDefinition` in two significant ways:

1. It does not store attributes such as property names or take any inputs. Generation of properties is done by adding additional operations such `CreateProperty`, `CreateComputedProperty` and `CreateSpreadProperty`.

2. The instructions that follow a `BeginObjectCreation` can only be of the type `CreateProperty`, `CreateComputedProperty` and `CreateSpreadProperty`. Unlike `BeginClassDefinition` where the instructions that follow the block start describe the class constructor.

# Design Considerations:
## Context and Scope changes
* We would need to add an additional context to the Context Analyzer to track object creation context.

## Semantic validation and code checks
* Similar to class semantic verification; we need to ensure that getters/setters are closed before starting new functions
* Similar block and scope management for `Begin*` operations
* We would also need a check to ensure that instructions that follow a `BeginObjectCreation` and before the block end should belong to the `CreateProperty*` family of instructions. Any other instructions should render the program invalid.

## AI handling
* BeginObjectCreation needs to be handled in executeOuterEffects (i.e. set(instr.output, object with properties)).
~TODO: How do we handle enumerating props/methods at this point. Could we have EndObjectCreation return an output instead of BeginObjectCreation?~(This would need a helper class such similar to ones defined in `ClassUtils.swift`)
* `BeginObjectCreation` does not generate a state change and we don't need to manage that. This is another deviation from `BeginClassDefinition` which requires a state change when processing the constructor. `Begin*` getter/setter creation ops will have state changes similar to how `BeginMethodDefinition` is modelled.

## Mutations
* Mutations would need to be context aware. As such we would need to have guards that ensure that `CreateProperty*` ops are only spliced or generated between `BeginObjectCreation` and the block end.
* The same mutation guards that prevent `BeginMethodDefinition` blocks from being spliced into other programs should be duplicated for `Begin*` getter/setters blocks. ~TODO: I haven't been able to find these guards for `BeginMethodDefinition`, could you point me to how and where this is implemented?~(#256 should address this)

## Minimization
* The generic block reduce should be able to minimize object creation blocks

## Program building and Lifting
These shouldn't be too hard once we've agreed on a model.

WDYT? My main concerns are around AI handling and Mutations which I think needs additional review. 
Also do let me know if there are there any other design considerations that I've not taken into account.

**Comment by saelo** [comment]
Nice, thanks for writing this up! I agree, it would be great to support these language features in FuzzIL!

My main concern with this approach is that it breaks the current FuzzIL property that code can be inserted everywhere without affecting the correctness of the resulting program (and things like the CodeGenMutator.swift currently rely on this).
The reason behind the design of the class definitions in FuzzIL are basically:
- Arbitrary code can still be inserted everywhere inside a class definition (since that'll just be the body of a method)
- The AI knows the proper instance type after processing just the `BeginClassDefinition`, which it needs to [properly type the `this` parameter inside class methods](https://github.com/googleprojectzero/fuzzilli/blob/4219480e371bd86a4eb5c2810e3ca37adc1a0a69/Sources/Fuzzilli/FuzzIL/AbstractInterpreter.swift#L507).

On the other hand, if we ever want to [properly support loop headers](https://github.com/googleprojectzero/fuzzilli/issues/8), then we'll anyway need to be able to define "restricted" contexts in which only certain instructions are allowed. This might then also allow simplifying things like class definitions, switch-case statements etc.

So I think it'd be worth exploring this idea further. We'll need a way to define these "restricted" contexts and define which operations are allowed inside them. In the simplest case, this could for example just be a function `IsOperationAllowedInContext(op, ctx)` in [Semantics.swift](https://github.com/googleprojectzero/fuzzilli/blob/main/Sources/Fuzzilli/FuzzIL/Semantics.swift). This then dictates which CodeGenerators are allowed to run, and certain Mutators need to then check this as well (e.g. [here](https://github.com/googleprojectzero/fuzzilli/blob/4219480e371bd86a4eb5c2810e3ca37adc1a0a69/Sources/Fuzzilli/Mutators/CombineMutator.swift#L25) I think), maybe via some kind of `ProgramBuilder.isInsideRestrictedContext` or something like that. Probably this should be based on the existing ContextAnalyzer? Also, I think it'd be great to verify the context requirements (in this case, that only these specific operations are allowed inside a `BeginObjectCreation`) in `Code.check`, so that at least in debug builds, we quickly find out if something breaks.

**Comment by saelo** [comment]
Now done with https://github.com/googleprojectzero/fuzzilli/commit/840c09e07f342c2210694ececd23ef8ac3d669d6 which makes sure that the new instructions can be spliced, but only into other object literals
