### ISSUE TITLE
Simplify Splicing

### ISSUE THREAD

**Issue by saelo** [googleprojectzero/fuzzilli#261]
Since splicing will potentially become yet more complex with https://github.com/googleprojectzero/fuzzilli/pull/256, I think it'd make sense to try and simplify the logic a bit, since it's an important part of the fuzzing logic, and so should be easy to understand/verify.

My suggestion would be to remove the code that supports rewiring inputs (so that the slice is directly connected to the host program through data-flow), and instead replace that with a simple variant of the InputMutator, the TypeAwareInputMutator, which takes type information into account. The idea here being that rewired splicing is roughly equivalent to a "normal" splice followed by an input mutation, the latter being much simpler to implement though.

Any thoughts?

**Comment by amarekano** [comment]
> The idea here being that rewired splicing is roughly equivalent to a "normal" splice followed by an input mutation, the latter being much simpler to implement though.

Presumably the inputs for mutation would be retrieved for the host program rather than the target? I think this would be the simpler approach but I fear we would be losing out on the _aspects_ of the existing inputs. For example if we have the following target program:
```
v1 = CreateObejct( with properties)
... instructions that modify v1 (e.g. adding/deleting properties, store/load props, etc)
CallFunction(x, v1)
```
So if we splice `CallFunction` and replace `v1` with an input from the host program that has the same type (i.e. object with same properties) then we'd lose out on the modification to `v1`. Not sure if it's worth the effort to preserve these _aspects_. 

Also, what would we do if there are no available inputs of the desired type in the host program?

**Comment by saelo** [comment]
So I think what you are describing are issues with the _current_ approach, where [variables are rewired directly during splicing](https://github.com/googleprojectzero/fuzzilli/blob/590b6b0df2c0c467d3686da2ce2786385a61b8f0/Sources/Fuzzilli/Core/ProgramBuilder.swift#L733).

What I'm proposing is to simplify the splice algorithm to never rewire inputs. So in your example, we would copy the entire `CreateObject` block (well, at least we should probably copy the entire block including its content if we need `v1`, I think?) and the `CallFunction` instruction. This would be one mutation (a `CodeGenMutation`) and we'd then execute the resulting program etc. Then, we'd also add a variant of the `InputMutator` that is aware of types. This could, during a subsequent mutation, modify the `CallFunction` instruction to use a different 2nd input, but one that has a "compatible" type. The result would then be roughly equivalent to a splice with rewired inputs. Except that it is simpler and happens over multiple mutations.

**Comment by amarekano** [comment]
Yep fair, that makes sense now. I'm in favour of the approach you've described above.

**Comment by saelo** [comment]
https://github.com/googleprojectzero/fuzzilli/pull/263
