### ISSUE TITLE
docker usage help

### ISSUE THREAD

**Issue by We5ter** [googleprojectzero/fuzzilli#308]
Hi Samuel, I followed the construction for docker `docker run -ti fuzzilli ./Fuzzilli --profile=v8 /home/fuzzer/v8/d8`, but I forgot to add `storagePath`.

Fuzzilli has found 1 crash, but I didn't see it in docker, has it been discarded? Thanks for your help.

BTW, Happy holiday!

**Comment by We5ter** [comment]
Maybe modify this line will solve this problem `let storagePath = args["--storagePath"] ??  "./output"`

**Comment by saelo** [comment]
Hi! Yeah, currently if you don't specify `--storagePath`, it won't write anything to disk: https://github.com/googleprojectzero/fuzzilli/blob/cde2e151ccdb1d34b73117ea89bdeb33ae921b13/Sources/FuzzilliCli/main.swift#L463

The main reason for that is that workers don't need disk storage: they simply send everything they find to a manager instance, which then writes it to disk. I guess we could require an explicit `--no-storage` flag to be passed for instances that are not workers or otherwise abort (I do like to be able to run without storage for quick testing locally). WDYT?

**Comment by We5ter** [comment]
Yeah, it's a good idea, maybe we need abort the fuzzilli cli running when people don't specify either`--no-storage` flag or `--storagePath` flag, a green hand like me always don’t notice that warning because the fuzzilli cli is still running.
