### ISSUE TITLE
Invalid parameter type for custom fuzzilli corpus

### ISSUE THREAD

**Issue by EmmaReuter** [googleprojectzero/fuzzilli#350]
I'm getting 
 
    typeDecodingError("invalid parameter type") Skipping

when loading the below compiled program using the fuzzilli compiler and --importCorpusAll
```
function main() {
function foo(x) {
        return x;
}

for(i = 0; i < 1000; i++) {
        foo(i);
}
}
main();
```

**Comment by saelo** [comment]
The [compiler](https://github.com/googleprojectzero/fuzzilli/tree/main/Compiler) is currently unmaintained and there have been a number of changes to Fuzzilli's IL so the compiler probably currently produces some invalid FuzzIL programs. Fuzzilli's IL is not yet stable, and we are also making changes to the IL specifically so that compilers have an easier job generating FuzzIL code. But it's not currently clear when we'll have a supported compiler, unfortunately...

**Comment by EmmaReuter** [comment]
Got it, Is there any way to generate a custom corpus right now?

**Comment by saelo** [comment]
No, sorry, there's no supported compiler at the moment. :( You could try hacking the existing one or [this one](https://github.com/oicu0619/fuzzilli-compiler) though... In any case, the [FuzzILTool](https://github.com/googleprojectzero/fuzzilli/tree/main/Sources/FuzzILTool) might be useful when generating FuzzIL programs.

**Comment by rromanw** [comment]
Could you make estimate, how much work would it be for a person who is not very familiar with the code? And could you tell us, which was the last known good configuration for the compiler?
