### ISSUE TITLE
Fix bugs in javascript generator for v8

### ISSUE THREAD

**Issue by thatreguy** [googleprojectzero/fuzzilli#39]
I get a lot of errors like this. Not sure if a valid js is getting created:
```
TypeError: Constructor _ requires 'new'
TypeError: undefined/_ is not a function
TypeError: Right-hand side of 'instanceof' is not an object
ReferenceError: _ is not defined
TypeError: Cannot read property _ of undefined

```
Here's how I'm running the crashes for repro

`timeout 5 /usr/local/src/v8/out/fuzzbuild/d8 --debug-code --expose-gc --single-threaded --predictable -allow-natives-syntax --interrupt-budget=10240 $filename
`

But even without any extra options to d8, I get the same result in most cases.

**Comment by saelo** [comment]
Is that for supposedly crashing programs or just programs generated during fuzzing? In the latter case, those are expected to be invalid JavaScript programs rather frequently. However, if the generated samples are in fact syntactically (not semantically!) invalid JavaScript, then that would be a bug in the JS Lifter.
If it's for supposedly crashing programs then it could be that during fuzzing the programs crash due to e.g. OOM but don't crash when reproing. It's hard to tell without more context. You could try to comment out this line https://github.com/googleprojectzero/fuzzilli/blob/2e7c967d171a5059aff6f9ab8df6be0e36216018/Sources/libreprl/libreprl.c#L106 then you should get stderr of the child printed during fuzzing, which would tell you how the samples initially crashed (which might then hint as to why they don't reproduce).

**Comment by thatreguy** [comment]
This is for samples which are failing the d8 compiler's primitive sanity checks(thereby crashing it) during fuzzing
They are not crashing due to OOM.
E.g.:

```
/usr/local/src/v8/out/fuzzbuild/d8 --debug-code --expose-gc --single-threaded --predictable -allow-natives-syntax --interrupt-budget=10240 ./crash_1563992803213_4983_deterministic_4.js
[COV] no shared memory bitmap available, skipping
[COV] edge counters initialized. Shared memory: (null) with 560233 edges
./crash_1563992803213_4983_deterministic_4.js:12: TypeError: Constructor ArrayBuffer requires 'new'
        const v18 = ArrayBuffer();
                    ^
TypeError: Constructor ArrayBuffer requires 'new'
    at ArrayBuffer (<anonymous>)
    at v8 (./crash_1563992803213_4983_deterministic_4.js:12:21)
    at main (./crash_1563992803213_4983_deterministic_4.js:14:17)
    at ./crash_1563992803213_4983_deterministic_4.js:18:1

/usr/local/src/v8/out/fuzzbuild/d8 --debug-code --expose-gc --single-threaded --predictable -allow-natives-syntax --interrupt-budget=10240 ./crash_1563999155584_18632_deterministic_4.js
[COV] no shared memory bitmap available, skipping
[COV] edge counters initialized. Shared memory: (null) with 560233 edges
./crash_1563999155584_18632_deterministic_4.js:50: TypeError: Right-hand side of 'instanceof' is not an object
const v71 = 13.37 instanceof v59;
                  ^
TypeError: Right-hand side of 'instanceof' is not an object
    at main (./crash_1563999155584_18632_deterministic_4.js:50:19)
    at ./crash_1563999155584_18632_deterministic_4.js:55:1```

**Comment by saelo** [comment]
No that wouldn't be treated as a crash by Fuzzilli. It's a runtime exception so the process will exit normally with return code != 0.

**Comment by saelo** [comment]
I'm now tracking attempts to improve handling of non-reproducible crashes here: https://github.com/googleprojectzero/fuzzilli/issues/42
