### ISSUE TITLE
Adding Additional Targets

### ISSUE THREAD

**Issue by WilliamParks** [googleprojectzero/fuzzilli#73]
@saelo, what are your thoughts on adding additional targets to Fuzzilli?

I've got it running on [duktape](https://github.com/svaarala/duktape), and have found a handful of bugs (including some to add to the showcase shortly!).

The maintainer there is interested as well, but I didn't want to commit anyone to maintaining the additional target, as I personally cannot. Thanks!

**Comment by saelo** [comment]
Great! Yeah I'll happily merge code that adds support for additional targets into Fuzzilli. That said, I likely won't be maintaining support for targets that am not fuzzing myself either. However, IMO there is definitely value in having the patches etc. in Fuzzilli even if they are outdated, since it's most likely easier to rebase an existing patchset onto a newer version than to develop a new one from scratch.

**Comment by WilliamParks** [comment]
Cool! I'll get something together for another PR.

It looks like it'll be implemented with a make target on the duktape side, rather than a patch in Fuzzilli. The main thing would be making sure the profile continues to compile, if the base profile struct itself is updated.

**Comment by saelo** [comment]
Ah great, that's even better. Yeah the DuktapeProfile will always be compiled into Fuzzilli, so if something in the base Profile struct changes, the build will fail and whoever changed the Profile struct will have to fix the DuktapeProfile :)

**Comment by WilliamParks** [comment]
Closed by #77
